// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dayxthvohymscaxyywpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRheXh0aHZvaHltc2NheHl5d3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczOTQyNzAsImV4cCI6MjA2Mjk3MDI3MH0.NjvD5oSfrCOaAmuHhhnwci815kfvurTgraBs3kVXeWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);